name: content_site
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  jaspr: ^0.18.0
  jaspr_content: ^0.1.0
  jaspr_router: ^0.6.3

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.1.1
  jaspr_builder: ^0.18.0
  jaspr_lints: ^0.3.1
  lints: ^5.0.0

dependency_overrides:
  jaspr_content: 
    path: ../../packages/jaspr_content

jaspr:
  mode: static

