name: package_riverpod
description: An example showing how to use riverpod with jaspr.
version: 0.1.6
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  jaspr: ^0.19.0
  jaspr_riverpod: ^0.3.20

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.1.0
  jaspr_builder: ^0.19.1
  jaspr_lints: ^0.4.0
  lints: ^5.0.0

jaspr:
  mode: server
