name: backend_dart_frog
description: An example application built with dart_frog & jaspr.
version: 0.1.6
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  jaspr: ^0.19.0
  shelf: ^1.4.2

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  jaspr_builder: ^0.19.1
  jaspr_lints: ^0.4.0
  lints: ^5.0.0

dependency_overrides:
  hotreloader: ^4.1.0

jaspr:
  mode: server
  dev-command: dart_frog dev
