name: flutter_multi_view
description: A new jaspr project.
version: 0.0.5
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  jaspr: ^0.19.0
  jaspr_flutter_embed: ^0.4.6

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.1.0
  jaspr_builder: ^0.19.1
  jaspr_lints: ^0.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

jaspr:
  mode: static

flutter:
  uses-material-design: true
