name: example_server
description: Starting point for a Serverpod server.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  jaspr: ^0.19.0
  jaspr_serverpod: ^0.5.0
  serverpod: 2.3.0

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.1.0
  jaspr_builder: ^0.19.1
  jaspr_lints: ^0.4.0
  lints: ^5.0.0

jaspr:
  mode: server
  dev-command: dart bin/main.dart --apply-migrations
